# Error Handling

- book: [Error Handling](https://doc.rust-lang.org/book/ch09-00-error-handling.html)

Rust doesnâ€™t have exceptions.

- `Result<T, E>`: recoverable error
   - like: file not found
   - want to retry
- `panic!`: unrecoverable error
   - like: access a location beyond the end of an array
   - want to immediately stop

## Start

### Panic

- [panic/src/main.rs](panic/src/main.rs)

```rs
panic!("crash and burn");
```

1. print a failure message
2. **unwind**, clean up the stack
3. quit

#### switch to Immediately Aborting

`Cargo.toml`:

```toml
[profile.release]
panic = 'abort'
```

#### Output

```bash
RUST_BACKTRACE=1 cargo run
   Compiling panic v0.1.0 (rust/src/learn/errors/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.84s
     Running `target/debug/panic`
thread 'main' panicked at 'crash and burn', src/main.rs:2:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: panic::main
             at ./src/main.rs:2:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Recover

- [panic/src/main.rs](panic/src/main.rs)

#### Shorten Error Recover

before:

```rs
let greeting_file_result = File::open("hello.txt");

let greeting_file = match greeting_file_result {
   Ok(file) => file,
   Err(error) => match error.kind() {
      ErrorKind::NotFound => match File::create("hello.txt") {
            Ok(fc) => fc,
            Err(e) => panic!("Problem creating the file: {:?}", e),
      },
      other_error => {
            panic!("Problem opening the file: {:?}", other_error);
      }
   },
};
```

after:

```rs
let gretting_file = File::open("hello.txt").unwrap_or_else(|error| {
   if error.kind() == ErrorKind::NotFound {
      File::create("hello.txt").unwrap_or_else(|error| {
            panic!("Problem creating the file: {:?}", error);
      })
   } else {
      panic!("Problem opening the file: {:?}", error);
   }
});
```

#### ? operator

```rs
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();
    File::open("hello.txt")?.read_to_string(&mut username)?;
    Ok(username)
}
```

```rs
fn last_char_of_first_line(text: &str) -> Option<char> {
    text.lines().next()?.chars().last()
}
```

### Custom Types for Validation

- [guessing game](/src/learn/guessing_game/src/main.rs)

```rs
// thread 'main' panicked at 'The secret number will be between 1 and 100.'
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("The secret number will be between 1 and 100.");
        }

        Guess { value }
    }

    pub fn value(&self) -> i32 {
        self.value
    }
}
```

